@startuml "Point.Social"
'https://plantuml.com/class-diagram

class PointSocial
class SoicialProfile
class SocialContent
abstract PointIdetifiedUupsProxyble
abstract Migratable

abstract Initializable
abstract UUPSUpgradeable
abstract OwnableUpgradeable

interface ISocialProfile
interface ISocialContent

PointSocial o-- SoicialProfile
PointSocial o-- SocialContent

SoicialProfile <|.. ISocialProfile
SocialContent <|.. ISocialContent

PointSocial <|.. PointIdetifiedUupsProxyble
SoicialProfile <|.. PointIdetifiedUupsProxyble
SocialContent <|.. PointIdetifiedUupsProxyble

PointSocial <|.. Migratable
SoicialProfile <|.. Migratable
SocialContent <|.. Migratable

PointIdetifiedUupsProxyble <|-- Initializable
PointIdetifiedUupsProxyble <|-- UUPSUpgradeable
PointIdetifiedUupsProxyble <|-- OwnableUpgradeable

enum Action {
    INIT,
    ADD,
    DELETE
}

Migratable *-- Action

@enduml