@startuml "Point.Social"
'https://plantuml.com/class-diagram

class SoicialProfile
class SocialContent
abstract PointIdUupsProxyble
abstract Migratable

abstract Initializable
abstract UUPSUpgradeable
abstract OwnableUpgradeable

interface ISocialProfile
interface ISocialContent

SocialRouter o-- SoicialProfile
SocialRouter o-- SocialContent

SoicialProfile <|.. ISocialProfile
SocialContent <|.. ISocialContent

SocialRouter <|.. PointIdUupsProxyble
SoicialProfile <|.. PointIdUupsProxyble
SocialContent <|.. PointIdUupsProxyble

SoicialProfile <|.. Migratable
SocialContent <|.. Migratable

PointIdUupsProxyble <|-- Initializable
PointIdUupsProxyble <|-- UUPSUpgradeable
PointIdUupsProxyble <|-- OwnableUpgradeable

enum Action {
    INIT,
    ADD,
    DELETE
}

Migratable *-- Action

@enduml