@startuml "Point.Social"
'https://plantuml.com/class-diagram

class SoicialProfile
class SocialContent
class IdentityUtils
class Identity

abstract PointIdUupsProxyble
abstract Migratable

abstract Initializable
abstract UUPSUpgradeable
abstract OwnableUpgradeable

interface ISocialProfile
interface ISocialContent
interface IIdentity

SocialRouter o-- SoicialProfile
SocialRouter o-- SocialContent
IdentityUtils o-- Idenity
SoicialProfile o-- IdentityUtils
SocialContent o-- IdentityUtils

SoicialProfile <|.. ISocialProfile
SocialContent <|.. ISocialContent
Identity <|.. IIdentity

SocialRouter <|.. PointIdUupsProxyble
SoicialProfile <|.. PointIdUupsProxyble
SocialContent <|.. PointIdUupsProxyble

SoicialProfile <|.. Migratable
SocialContent <|.. Migratable

Initializable <|-- PointIdUupsProxyble
UUPSUpgradeable <|-- PointIdUupsProxyble
OwnableUpgradeable <|-- PointIdUupsProxyble

enum MigrationAction {
    INIT,
    ADD,
    DELETE
}

enum SocialAction {
        Create,
        Like,
        Comment,
        Edit,
        Delete,
        Dislike,
        Flag
}

enum SocialComponent {
        Feed,
        Post,
        Comment
}

Migratable *-- MigrationAction
SocialContent *-- SocialAction
SocialContent *-- SocialComponent

@enduml